name: Deploy AWS Lambda

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        id: setup_node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install Dependencies if Lambda exists
      - name: Install Dependencies
        id: install_dependencies
        if: hashFiles('lambda/package.json') != ''
        run: |
          cd lambda
          npm install

      # 4️⃣ Lambda Syntax Check
      - name: Lambda Syntax Check
        id: syntax_check
        run: |
          cd lambda
          npx eslint . --ext .js

      # 5️⃣ Run Lambda Tests
      - name: Run Lambda Tests
        id: run_tests
        if: hashFiles('lambda/tests/**') != ''
        continue-on-error: true
        run: |
          set -e
          node lambda/tests/test_lambda.js

      # 6️⃣ Detect Changed Services
      - name: Detect Changed Services
        id: detect
        run: |
          echo "services=[]" >> $GITHUB_ENV
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            changed_files=$(git diff --name-only HEAD~1 HEAD)
          else
            echo "No previous commit found (first push). Considering all services."
            changed_files=$(find lambda -type f)
          fi

          services=()
          if echo "$changed_files" | grep -q "lambda/"; then
            services+=("lambda")
          fi

          echo "services=${services[*]}" >> $GITHUB_ENV
          echo "Detected services: ${services[*]}"

      # 7️⃣ Zip Lambda code
      - name: Zip Lambda code
        id: zip_lambda
        if: contains(env.services, 'lambda')
        run: |
          cd lambda
          zip -r ../lambda_deploy.zip . -x "tests/*" "node_modules/*"

      # 8️⃣ Setup Terraform
      - name: Setup Terraform
        id: setup_terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      # 9️⃣ Ensure Terraform Backend S3 Bucket Exists
      - name: Ensure Terraform Backend
        id: ensure_backend
        run: |
          if aws s3 ls "s3://esh-terra" 2>&1 | grep -q 'NoSuchBucket'; then
            echo "🪣 Creating Terraform state bucket..."
            aws s3api create-bucket \
              --bucket esh-terra \
              --region us-east-1 \
              --create-bucket-configuration LocationConstraint=us-east-1
          else
            echo "✅ Backend bucket already exists"
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      # 🔟 Terraform Init
      - name: Terraform Init
        id: tf_init
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: terraform init -reconfigure -input=false

      # 1️⃣1️⃣ Import existing Lambda if it exists
      - name: Import existing Lambda
        id: import_lambda
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          set -e
          FUNCTION_NAME="demo_service"
          if aws lambda get-function --function-name "$FUNCTION_NAME" >/dev/null 2>&1; then
            echo "🟢 Lambda '$FUNCTION_NAME' exists — importing into Terraform state..."
            terraform init -reconfigure -input=false
            if terraform state list | grep -q "aws_lambda_function.demo_lambda"; then
              echo "🔹 Already imported into Terraform state."
            else
              terraform import \
                -var="region=us-east-1" \
                -var="lambda_zip=../lambda_deploy.zip" \
                -var="lambda_handler=index.handler" \
                -var="lambda_runtime=nodejs18.x" \
                -var="lambda_role=${{ secrets.LAMBDA_ROLE_ARN }}" \
                aws_lambda_function.demo_lambda "$FUNCTION_NAME"
            fi
          else
            echo "🆕 Lambda '$FUNCTION_NAME' does not exist — will be created by Terraform."
          fi

      # 1️⃣2️⃣ Capture current Lambda alias version (for rollback)
      - name: Capture current Lambda alias version
        id: capture_version
        run: |
          FUNCTION_NAME="demo_service"
          ALIAS_NAME="prod"

          if aws lambda get-alias --function-name "$FUNCTION_NAME" --name "$ALIAS_NAME" >/dev/null 2>&1; then
            CURRENT_VERSION=$(aws lambda get-alias --function-name "$FUNCTION_NAME" --name "$ALIAS_NAME" --query 'FunctionVersion' --output text)
            echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
            echo "Alias exists. Current version: $CURRENT_VERSION"
          else
            echo "Alias does not exist yet. No rollback possible."
            echo "CURRENT_VERSION=" >> $GITHUB_ENV
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      # 1️⃣3️⃣ Terraform Apply (Lambda Only)
      - name: Terraform Apply (Lambda Only)
        id: apply
        working-directory: terraform
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          set -e
          terraform apply -auto-approve \
            -var="region=us-east-1" \
            -var="lambda_zip=../lambda_deploy.zip" \
            -var="lambda_handler=index.handler" \
            -var="lambda_runtime=nodejs18.x" \
            -var="lambda_role=${{ secrets.LAMBDA_ROLE_ARN }}" \
            -input=false

      # 1️⃣4️⃣ Rollback Lambda alias if apply fails
      - name: Rollback Lambda alias if apply fails
        id: rollback
        if: failure()
        run: |
          if [ -n "$CURRENT_VERSION" ]; then
            echo "Terraform apply failed. Rolling back Lambda alias..."
            aws lambda update-alias \
              --function-name demo_service \
              --name prod \
              --function-version "$CURRENT_VERSION"
          else
            echo "No previous alias version found. Skipping rollback."
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      # 1️⃣5️⃣ Build failure summary (to detect where it failed)
      - name: Build failure summary
        id: build_summary
        if: failure()
        run: |
          FAILURE_MESSAGE="❌ Lambda deployment pipeline failed at unknown step."

          if [ "${{ steps.syntax_check.outcome }}" == "failure" ]; then
            FAILURE_MESSAGE="❌ Failed during Lambda Syntax Check."
          elif [ "${{ steps.run_tests.outcome }}" == "failure" ]; then
            FAILURE_MESSAGE="❌ Failed during Lambda Tests."
          elif [ "${{ steps.zip_lambda.outcome }}" == "failure" ]; then
            FAILURE_MESSAGE="❌ Failed during Zipping Lambda Code."
          elif [ "${{ steps.tf_init.outcome }}" == "failure" ]; then
            FAILURE_MESSAGE="❌ Failed during Terraform Init."
          elif [ "${{ steps.import_lambda.outcome }}" == "failure" ]; then
            FAILURE_MESSAGE="❌ Failed during Terraform Import."
          elif [ "${{ steps.apply.outcome }}" == "failure" ]; then
            FAILURE_MESSAGE="❌ Failed during Terraform Apply."
          fi

          echo "FAILURE_MESSAGE=$FAILURE_MESSAGE" >> $GITHUB_ENV

      # 1️⃣6️⃣ SNS Notification with Logs
      - name: SNS Notification with Logs
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          SNS_TOPIC_ARN: arn:aws:sns:us-east-1:612572392212:LambdaDeployNotifications-e
        run: |
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          if [ "${{ job.status }}" == "success" ] && [ "${{ steps.run_tests.outcome }}" == "success" ]; then
            MESSAGE="✅ Lambda deployment pipeline succeeded!
Branch: ${{ github.ref }}
Commit: ${{ github.sha }}
Logs: $RUN_URL"
          else
            MESSAGE="${FAILURE_MESSAGE}
Branch: ${{ github.ref }}
Commit: ${{ github.sha }}
Logs: $RUN_URL"
          fi

          aws sns publish \
            --topic-arn "$SNS_TOPIC_ARN" \
            --message "$MESSAGE" \
            --region $AWS_DEFAULT_REGION
