name: Deploy AWS Lambda

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies (if Lambda exists)
        if: hashFiles('lambda/package.json') != ''
        run: |
          cd lambda
          npm install

      - name: Run Lambda Tests
        if: hashFiles('lambda/tests/**') != ''
        run: |
          node lambda/tests/test_lambda.js

      - name: Detect Changed Services
        id: detect
        run: |
          echo "services=[]" >> $GITHUB_ENV
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            changed_files=$(git diff --name-only HEAD~1 HEAD)
          else
            echo "No previous commit found (first push). Considering all services."
            changed_files=$(find lambda -type f)
          fi

          services=()
          if echo "$changed_files" | grep -q "lambda/"; then
            services+=("lambda")
          fi

          echo "services=${services[*]}" >> $GITHUB_ENV
          echo "Detected services: ${services[*]}"

      - name: Zip Lambda code
        if: contains(env.services, 'lambda')
        run: |
          cd lambda
          zip -r ../lambda_deploy.zip . -x "tests/*" "node_modules/*"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Ensure Terraform Backend S3 Bucket Exists
        run: |
          if aws s3 ls "s3://esh-terra" 2>&1 | grep -q 'NoSuchBucket'; then
            echo "🪣 Creating Terraform state bucket..."
            aws s3api create-bucket \
              --bucket esh-terra \
              --region us-east-1 \
              --create-bucket-configuration LocationConstraint=us-east-1
          else
            echo "✅ Backend bucket already exists"
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Terraform Init
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: terraform init -reconfigure -input=false

      - name: Import existing Lambda (if needed)
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          set -e
          FUNCTION_NAME="demo_service"

          if aws lambda get-function --function-name "$FUNCTION_NAME" >/dev/null 2>&1; then
            echo "🟢 Lambda '$FUNCTION_NAME' exists — importing into Terraform state..."
            terraform init -reconfigure -input=false

            if terraform state list | grep -q "aws_lambda_function.demo_lambda"; then
              echo "🔹 Already imported into Terraform state."
            else
              terraform import \
                -var="region=us-east-1" \
                -var="lambda_zip=../lambda_deploy.zip" \
                -var="lambda_handler=index.handler" \
                -var="lambda_runtime=nodejs18.x" \
                -var="lambda_role=${{ secrets.LAMBDA_ROLE_ARN }}" \
                aws_lambda_function.demo_lambda "$FUNCTION_NAME"
            fi
          else
            echo "🆕 Lambda '$FUNCTION_NAME' does not exist — will be created by Terraform."
          fi
      
      - name: Capture current Lambda alias version
        id: capture_version
        run: |
          CURRENT_VERSION=$(aws lambda get-alias --function-name demo_service --name prod --query 'FunctionVersion' --output text)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Terraform Apply (Lambda Only)
        id: apply
        working-directory: terraform
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          set -e
          terraform apply -auto-approve \
            -var="region=us-east-1" \
            -var="lambda_zip=../lambda_deploy.zip" \
            -var="lambda_handler=index.handler" \
            -var="lambda_runtime=nodejs18.x" \
            -var="lambda_role=${{ secrets.LAMBDA_ROLE_ARN }}" \
            -input=false

      - name: Rollback Lambda alias if apply fails
        if: failure()
        run: |
          echo "Terraform apply failed. Rolling back Lambda alias..."
          aws lambda update-alias \
            --function-name demo_service \
            --name prod \
            --function-version $CURRENT_VERSION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1


      - name: SNS Notification with Logs
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          SNS_TOPIC_ARN: arn:aws:sns:us-east-1:612572392212:LambdaDeployNotifications-e
        run: |
          # Capture last 100 lines of workflow log for debugging
          LOGS=$(tail -n 100 $GITHUB_WORKSPACE/_temp/_runner_file_commands/set_env_* 2>/dev/null || echo "No logs available")
          
          if [ "${{ job.status }}" == "success" ]; then
            MESSAGE="✅ Lambda deployment pipeline succeeded! Branch: ${{ github.ref }}, Commit: ${{ github.sha }}"
          else
            MESSAGE="❌ Lambda deployment pipeline failed! Branch: ${{ github.ref }}, Commit: ${{ github.sha }}\n\nLast 100 lines of logs:\n$LOGS"
          fi

          aws sns publish \
            --topic-arn "$SNS_TOPIC_ARN" \
            --message "$MESSAGE" \
            --region $AWS_DEFAULT_REGION
